/* 추천 시스템에 따른 결과(ex. 1시간마다 업데이트됨)는 Redis에 서빙할 예정*/

/* =======================
   확장 (Extensions)
   ======================= */
-- pgvector 확장 활성화 (벡터 임베딩 검색용)
CREATE EXTENSION IF NOT EXISTS vector;

/* =======================
   1. 사용자 기본 정보
   ======================= */
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    gender TEXT CHECK (gender IN ('male', 'female')),
    has_completed_onboarding BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN users.gender IS '사용자 성별';
COMMENT ON COLUMN users.has_completed_onboarding IS '온보딩(선호도 설정) 완료 여부';


/* =======================
   2. 판매하는 개별 상품
   ======================= */
CREATE TABLE items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    category TEXT CHECK (category IN ('top', 'bottom', 'outer')) NOT NULL,
    brand_name_ko VARCHAR(100),
    price DECIMAL(10, 2),
    purchase_url VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_items_category ON items(category);
CREATE INDEX idx_items_brand_ko ON items(brand_name_ko);


/* =======================
   3. 코디
   ======================= */
CREATE TABLE coordis (
    coordi_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season TEXT CHECK (season IN ('spring', 'summer', 'fall', 'winter')),
    style TEXT CHECK (style IN ('casual', 'street', 'sporty', 'minimal')),
    gender TEXT CHECK (gender IN ('male', 'female')),
    description TEXT,
    description_embedding vector(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN coordis.season IS '4계절 (필터링용)';
COMMENT ON COLUMN coordis.style IS '코디 무드/스타일';
COMMENT ON COLUMN coordis.gender IS '코디 대상 성별';
COMMENT ON COLUMN coordis.description IS '태그 포함 설명 문구';
COMMENT ON COLUMN coordis.description_embedding IS '의미 검색을 위한 Description 임베딩 벡터(512차원)';
CREATE INDEX idx_coordis_season_style ON coordis(season, style);
CREATE INDEX idx_coordis_style ON coordis(style);
-- 벡터 검색을 위한 인덱스 (코사인 유사도 검색용)
-- ivfflat 인덱스는 데이터가 많을 때 성능 향상
-- lists 파라미터는 데이터 양에 따라 조정 (일반적으로 sqrt(총_레코드_수))
CREATE INDEX idx_coordis_embedding ON coordis 
USING ivfflat (description_embedding vector_cosine_ops)
WITH (lists = 100);


/* =======================
   4. 태그
   ======================= */
CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN tags.name IS '태그 이름 (예: #캐주얼)';


/* =======================
   5. 가상 피팅 결과
   ======================= */
CREATE TABLE fitting_results (
    fitting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status TEXT CHECK (status IN ('processing', 'completed', 'failed', 'timeout')) DEFAULT 'processing',
    current_step TEXT CHECK (current_step IN ('top', 'bottom', 'outer')),
    failed_step TEXT CHECK (failed_step IN ('top', 'bottom', 'outer')),
    llm_message TEXT,
    finished_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

COMMENT ON COLUMN fitting_results.status IS '피팅 작업 상태';
COMMENT ON COLUMN fitting_results.current_step IS '현재 처리 단계 (processing 상태일 때)';
COMMENT ON COLUMN fitting_results.failed_step IS '실패한 단계 (failed 상태일 때)';
COMMENT ON COLUMN fitting_results.llm_message IS 'LLM 평가 메시지';
COMMENT ON COLUMN fitting_results.finished_at IS '작업 완료/실패/타임아웃 시점 (status가 completed/failed/timeout일 때)';
CREATE INDEX idx_fitting_results_user ON fitting_results(user_id);


/* =======================
   5-1. 사용자 이미지
   ======================= */
CREATE TABLE user_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    image_url VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

COMMENT ON COLUMN user_images.image_url IS '사용자의 전신 사진 URL';
CREATE INDEX idx_user_images_user ON user_images(user_id);


/* =======================
   5-2. 아이템 이미지
   ======================= */
CREATE TABLE item_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    image_url VARCHAR(1024) NOT NULL,
    is_main BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

COMMENT ON COLUMN item_images.is_main IS '대표 썸네일 여부';
CREATE INDEX idx_item_images_item ON item_images(item_id, is_main);


/* =======================
   5-3. 코디 이미지
   ======================= */
CREATE TABLE coordi_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coordi_id BIGINT NOT NULL,
    image_url VARCHAR(1024) NOT NULL,
    is_main BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (coordi_id) REFERENCES coordis(coordi_id) ON DELETE CASCADE
);

COMMENT ON COLUMN coordi_images.is_main IS '대표 썸네일 여부';
CREATE INDEX idx_coordi_images_coordi ON coordi_images(coordi_id, is_main);


/* =======================
   5-4. 가상 피팅 결과 이미지
   ======================= */
CREATE TABLE fitting_result_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fitting_id BIGINT NOT NULL,
    image_url VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (fitting_id) REFERENCES fitting_results(fitting_id) ON DELETE CASCADE
);

COMMENT ON COLUMN fitting_result_images.image_url IS 'AI가 생성한 피팅 결과물 URL';
CREATE INDEX idx_fitting_result_images_fitting ON fitting_result_images(fitting_id);


/* =======================
   6. 사용자 선호 태그 N:M
   ======================= */
CREATE TABLE user_preferred_tags (
    user_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (user_id, tag_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(tag_id) ON DELETE CASCADE
);

COMMENT ON TABLE user_preferred_tags IS '사용자와 선호 태그의 N:M 관계 테이블';


/* =======================
   7. 피팅 결과 - 아이템 N:M
   ======================= */
CREATE TABLE fitting_result_items (
    fitting_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,

    PRIMARY KEY (fitting_id, item_id),
    FOREIGN KEY (fitting_id) REFERENCES fitting_results(fitting_id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

COMMENT ON TABLE fitting_result_items IS '가상 피팅 결과와 아이템의 N:M 관계 테이블';
CREATE INDEX idx_fitting_result_items_item ON fitting_result_items(item_id);


/* =======================
   8. 코디 - 아이템 N:M
   ======================= */
CREATE TABLE coordi_items (
    coordi_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    
    PRIMARY KEY (coordi_id, item_id),
    FOREIGN KEY (coordi_id) REFERENCES coordis(coordi_id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

COMMENT ON TABLE coordi_items IS '코디와 아이템의 N:M 관계 테이블';
CREATE INDEX idx_coordi_items_item ON coordi_items(item_id);


/* =======================
   9. 사용자 코디 스와이프 이력
   ======================= */
CREATE TABLE user_coordi_interactions (
    user_id BIGINT NOT NULL,
    coordi_id BIGINT NOT NULL,
    action_type TEXT CHECK (action_type IN ('like', 'skip', 'preference')) NOT NULL,
    interacted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (user_id, coordi_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (coordi_id) REFERENCES coordis(coordi_id) ON DELETE CASCADE
);

COMMENT ON TABLE user_coordi_interactions IS '사용자와 코디의 N:M 관계 테이블 (스와이프 이력)';
CREATE INDEX idx_user_coordi_interactions_coordi ON user_coordi_interactions(coordi_id, action_type);


/* =======================
   10. 코디 상세 조회 로그
   ======================= */
CREATE TABLE user_coordi_view_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    coordi_id BIGINT NOT NULL,
    view_started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_seconds INT NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (coordi_id) REFERENCES coordis(coordi_id) ON DELETE CASCADE
);

COMMENT ON COLUMN user_coordi_view_logs.view_started_at IS '조회 시작 시간';
COMMENT ON COLUMN user_coordi_view_logs.duration_seconds IS '머무른 시간 (초)';
CREATE INDEX idx_user_coordi ON user_coordi_view_logs(user_id, coordi_id);
CREATE INDEX idx_coordi_view_logs_coordi_time ON user_coordi_view_logs(coordi_id, view_started_at);


/* =======================
   11. 사용자 옷장
   ======================= */
CREATE TABLE user_closet_items (
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (user_id, item_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

COMMENT ON TABLE user_closet_items IS '사용자와 아이템의 N:M 관계 테이블 (옷장)';
CREATE INDEX idx_user_closet_items_item ON user_closet_items(item_id);
