"""test setup

Revision ID: 0acdf4bed72e
Revises: 
Create Date: 2025-11-12 19:04:50.296944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0acdf4bed72e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Coordi_Images',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.add_column(
        'Coordis',
        sa.Column(
            'gender',
            sa.Enum('MALE', 'FEMALE', name='coordi_gender_enum'),
            nullable=True,
            comment='코디 대상 성별',
        ),
    )
    op.alter_column(
        'Coordis',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('Fitting_Result_Images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('Fitting_Results', sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='fitting_result_status_enum'), server_default='PROCESSING', nullable=False, comment='피팅 작업 상태'))
    op.alter_column('Fitting_Results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_fitting_results_user_item', table_name='Fitting_Results')
    op.create_index('idx_fitting_results_user', 'Fitting_Results', ['user_id'], unique=False)
    op.drop_constraint('Fitting_Results_item_id_fkey', 'Fitting_Results', type_='foreignkey')
    op.drop_column('Fitting_Results', 'item_id')
    op.alter_column('Item_Images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Closet_Items', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Coordi_Interactions', 'interacted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Coordi_View_Logs', 'view_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Item_View_Logs', 'view_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    user_gender_enum = sa.Enum('MALE', 'FEMALE', name='user_gender_enum')
    user_gender_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'Users',
        'gender',
        existing_type=sa.VARCHAR(length=10),
        type_=user_gender_enum,
        comment='사용자 성별',
        existing_nullable=True,
        postgresql_using='gender::user_gender_enum',
    )
    op.alter_column(
        'Users',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Users',
        'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'Users',
        'gender',
        existing_type=sa.Enum('MALE', 'FEMALE', name='user_gender_enum'),
        type_=sa.VARCHAR(length=10),
        comment=None,
        existing_comment='사용자 성별',
        existing_nullable=True,
        postgresql_using='gender::text',
    )
    user_gender_enum = sa.Enum('MALE', 'FEMALE', name='user_gender_enum')
    user_gender_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('User_Item_View_Logs', 'view_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Coordi_View_Logs', 'view_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='조회 시작 시간',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Coordi_Interactions', 'interacted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('User_Closet_Items', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Item_Images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('Fitting_Results', sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='어떤 아이템을 피팅했는지'))
    op.create_foreign_key('Fitting_Results_item_id_fkey', 'Fitting_Results', 'Items', ['item_id'], ['item_id'], ondelete='CASCADE')
    op.drop_index('idx_fitting_results_user', table_name='Fitting_Results')
    op.create_index('idx_fitting_results_user_item', 'Fitting_Results', ['user_id', 'item_id'], unique=False)
    op.alter_column('Fitting_Results', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('Fitting_Results', 'status')
    op.alter_column('Fitting_Result_Images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Coordis', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('Coordis', 'gender')
    op.alter_column('Coordi_Images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
